version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.15.1-stretch-browsers
        env:
          - CHROME_BIN=/usr/bin/google-chrome
    steps:
      - checkout
      - run:
          name: Install latest version of npm
          command: sudo npm install -g npm@latest
      - run:
          name: Update node-sass bindings
          command: npm rebuild node-sass
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install local dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Run test suite
          command: npm run test
      - run:
          name: Build
          command: ng build --prod --base-href '/incremental/'
      - run:
          name: Deploy to github pages if on master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npx angular-cli-ghpages --dir=dist/incremental
            fi
